dist: trusty
language: java
sudo: required
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
  chrome: stable
cache:
  directories:
    - $HOME/.m2
    - $HOME/.selion/downloads
env:
  global:
    - DISPLAY=:99.0
  matrix:
    - TARGET=firefox
matrix:
  allow_failures:
    - env: TARGET=firefox
  fast_finish: true
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; sleep 3; fi
  - echo "MAVEN_OPTS='-Xmx1g -Xms256m'" > ~/.mavenrc
script:
    - |
      if [[ $TRAVIS_OS_NAME == 'linux' ]] && [[ $TARGET == *"firefox"* ]]; then
        sh -e utilities/travis-run-firefox-tests.sh
      fi
